name: Deploy dbt docs

on:
  push:
    branches: [main]  # Use your default branch name
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy directly to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target  # Your dbt docs location
          branch: gh-pages
          clean: true